[package]
name = "longest_palindromic_substring"
version = "0.1.0"
authors = ["UMU618 <umu618@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
